### ISSUE TITLE
Handle non-C drive letters on Windows and Network mounts

### ISSUE THREAD

**Issue by larsvilhuber** [korenmiklos/here#7]
Following up on #5, Should be further enhanced to stop at any drive letter root (e.g. "`U:\`"), and possibly accomodate Windows network drive paths (`\\server\path`) to not fall into endless loop.

Alternative (or fail-safe) is to count the number of loops, and stop at some max number (20 or 50).

**Comment by korenmiklos** [comment]
Maybe stop once `cd ..` fails to change `c(pwd)`?

**Comment by larsvilhuber** [comment]
That's a good idea. Should work anywhere.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
